/**
 * 공항 상세 정보 (주소, 전화번호 등)
 */

interface AirportInfo {
  name: string;
  address: string;
  telephone: string;
  domestic: boolean; // 국내선 운항 여부
  international: boolean; // 국제선 운항 여부
}

// 주요 공항 정보 매핑
const airportInfoMap: Record<string, AirportInfo> = {
  // ── 한국 ──
  'ICN': {
    name: '인천국제공항',
    address: '인천광역시 중구 공항로 272',
    telephone: '1577-2600',
    domestic: false,
    international: true,
  },
  'GMP': {
    name: '김포국제공항',
    address: '서울특별시 강서구 하늘길 112',
    telephone: '02-2660-2114',
    domestic: true,
    international: true,
  },
  'PUS': {
    name: '김해국제공항',
    address: '부산광역시 강서구 공항진입로 108',
    telephone: '051-974-3114',
    domestic: true,
    international: true,
  },
  'CJU': {
    name: '제주국제공항',
    address: '제주특별자치도 제주시 공항로 2',
    telephone: '064-797-2114',
    domestic: true,
    international: true,
  },
  'TAE': {
    name: '대구국제공항',
    address: '대구광역시 동구 공항로 221',
    telephone: '053-980-5114',
    domestic: true,
    international: true,
  },
  'CJJ': {
    name: '청주국제공항',
    address: '충청북도 청주시 흥덕구 강내면 남사리 산55',
    telephone: '043-210-6114',
    domestic: true,
    international: true,
  },
  'KWJ': {
    name: '광주공항',
    address: '광주광역시 광산구 상무대로 420',
    telephone: '062-942-0114',
    domestic: true,
    international: false,
  },
  'RSU': {
    name: '여수공항',
    address: '전라남도 여수시 율촌면 여수산단1로 82',
    telephone: '061-683-5114',
    domestic: true,
    international: false,
  },
  'USN': {
    name: '울산공항',
    address: '울산광역시 북구 산업로 1103',
    telephone: '052-219-0114',
    domestic: true,
    international: false,
  },
  'KPO': {
    name: '포항경주공항',
    address: '경상북도 포항시 남구 동해면 공항로 57',
    telephone: '054-284-0114',
    domestic: true,
    international: false,
  },
  'WJU': {
    name: '원주공항',
    address: '강원특별자치도 횡성군 횡성읍 횡성로 166',
    telephone: '033-340-8114',
    domestic: true,
    international: false,
  },
  'KUV': {
    name: '군산공항',
    address: '전북특별자치도 군산시 공항로 63',
    telephone: '063-469-8114',
    domestic: true,
    international: false,
  },
  'SHO': {
    name: '속초양양국제공항',
    address: '강원특별자치도 양양군 손양면 동해대로 596',
    telephone: '033-670-7114',
    domestic: true,
    international: true,
  },
  'MWX': {
    name: '무안국제공항',
    address: '전라남도 무안군 망운면 공항로 970-260',
    telephone: '061-455-2114',
    domestic: true,
    international: true,
  },
  'HIN': {
    name: '사천공항',
    address: '경상남도 사천시 사천읍 비행장길 47',
    telephone: '055-851-0114',
    domestic: true,
    international: false,
  },

  // ── 동아시아 - 일본 ──
  'NRT': {
    name: '나리타 국제공항',
    address: '千葉県成田市古込1-1, Narita, Chiba, Japan',
    telephone: '+81-476-34-8000',
    domestic: true,
    international: true,
  },
  'HND': {
    name: '도쿄 하네다 국제공항',
    address: 'Hanedakuko, Ota City, Tokyo 144-0041, Japan',
    telephone: '+81-3-5757-8111',
    domestic: true,
    international: true,
  },
  'KIX': {
    name: '간사이 국제공항',
    address: '1 Senshu-kuko Kita, Izumisano, Osaka 549-0001, Japan',
    telephone: '+81-72-455-2500',
    domestic: true,
    international: true,
  },
  'FUK': {
    name: '후쿠오카 공항',
    address: 'Shimousui, Hakata Ward, Fukuoka 812-0003, Japan',
    telephone: '+81-92-621-6059',
    domestic: true,
    international: true,
  },
  'CTS': {
    name: '신치토세 공항',
    address: 'Bibi, Chitose, Hokkaido 066-0012, Japan',
    telephone: '+81-123-23-0111',
    domestic: true,
    international: true,
  },
  'NGO': {
    name: '주부 센트레아 국제공항',
    address: '1-1 Centrair, Tokoname, Aichi 479-0881, Japan',
    telephone: '+81-569-38-1195',
    domestic: true,
    international: true,
  },
  'OKA': {
    name: '나하 공항',
    address: '150 Kagamizu, Naha, Okinawa 901-0142, Japan',
    telephone: '+81-98-840-1179',
    domestic: true,
    international: true,
  },
  'KOJ': {
    name: '가고시마 공항',
    address: '822 Matsugen, Kirishima, Kagoshima 899-6404, Japan',
    telephone: '+81-995-58-2535',
    domestic: true,
    international: true,
  },
  'KMJ': {
    name: '구마모토 공항',
    address: '1802-2 Oyatsu, Mashiki, Kamimashiki, Kumamoto 861-2204, Japan',
    telephone: '+81-96-232-2311',
    domestic: true,
    international: true,
  },
  'NGS': {
    name: '나가사키 공항',
    address: '593 Morinokamigo, Omura, Nagasaki 856-0816, Japan',
    telephone: '+81-957-52-5555',
    domestic: true,
    international: true,
  },
  'KMQ': {
    name: '고마쓰 공항',
    address: 'Ukishima-machi, Komatsu, Ishikawa 923-0993, Japan',
    telephone: '+81-761-21-9803',
    domestic: true,
    international: true,
  },
  'UKB': {
    name: '고베 공항',
    address: 'Kobe Airport, Chuo Ward, Kobe, Hyogo 650-0048, Japan',
    telephone: '+81-78-304-7777',
    domestic: true,
    international: true,
  },
  'SDJ': {
    name: '센다이 공항',
    address: 'Shimomasu, Natori, Miyagi 989-2401, Japan',
    telephone: '+81-22-382-0080',
    domestic: true,
    international: true,
  },
  'KIJ': {
    name: '니가타 공항',
    address: '3710 Matsuhama-machi, Higashi Ward, Niigata 950-0001, Japan',
    telephone: '+81-25-275-2633',
    domestic: true,
    international: true,
  },
  'OIT': {
    name: '오이타 공항',
    address: '6-72 Shimobarusaki, Kunisaki, Oita 873-0421, Japan',
    telephone: '+81-978-67-1174',
    domestic: true,
    international: true,
  },
  'OKJ': {
    name: '오카야마 모모타로 공항',
    address: '303-6 Nishikoichiageta, Okayama 701-1131, Japan',
    telephone: '+81-86-294-5201',
    domestic: true,
    international: true,
  },
  'TAK': {
    name: '다카마쓰 공항',
    address: '1346-6 Konancho Okaminami, Takamatsu, Kagawa 761-1401, Japan',
    telephone: '+81-87-814-3355',
    domestic: true,
    international: true,
  },
  'MYJ': {
    name: '마쓰야마 공항',
    address: 'Minami-yoshida-machi, Matsuyama, Ehime 791-1104, Japan',
    telephone: '+81-89-972-5600',
    domestic: true,
    international: true,
  },
  'TKS': {
    name: '도쿠시마 아와오도리 공항',
    address: 'Wada, Matsushige, Itano, Tokushima 771-0212, Japan',
    telephone: '+81-88-699-2831',
    domestic: true,
    international: true,
  },
  'AOJ': {
    name: '아오모리 공항',
    address: 'Dainoda, Oaza-Takada, Aomori 030-0142, Japan',
    telephone: '+81-17-739-2121',
    domestic: true,
    international: true,
  },
  'HIJ': {
    name: '히로시마 공항',
    address: '64-31 Zennyuji, Hongo-cho, Mihara, Hiroshima 729-0416, Japan',
    telephone: '+81-848-86-8151',
    domestic: true,
    international: true,
  },
  'HSG': {
    name: '사가 공항',
    address: '1234-2 Kawasoe-machi Inuikomata, Saga 840-2212, Japan',
    telephone: '+81-952-46-0100',
    domestic: true,
    international: true,
  },
  'FSZ': {
    name: '후지산 시즈오카 공항',
    address: '500-2 Satozuka, Makinohara, Shizuoka 421-0411, Japan',
    telephone: '+81-548-29-2000',
    domestic: true,
    international: true,
  },
  'KMI': {
    name: '미야자키 공항',
    address: 'Oaza-Akaemi, Miyazaki 880-0912, Japan',
    telephone: '+81-985-51-5111',
    domestic: true,
    international: true,
  },
  'SHI': {
    name: '시모지시마 공항',
    address: 'Shimojishimo, Miyakojima, Okinawa 906-0507, Japan',
    telephone: '+81-980-78-6365',
    domestic: true,
    international: true,
  },
  'SHM': {
    name: '난키 시라하마 공항',
    address: '2926-1 Saino, Shirahama, Nishimuro, Wakayama 649-2201, Japan',
    telephone: '+81-739-42-3710',
    domestic: true,
    international: false,
  },
  'UBJ': {
    name: '야마구치 우베 공항',
    address: 'Okinouyama, Ube, Yamaguchi 755-0001, Japan',
    telephone: '+81-836-21-5841',
    domestic: true,
    international: true,
  },
  'ISG': {
    name: '이시가키 공항',
    address: '1020-61 Shiraho, Ishigaki, Okinawa 907-0242, Japan',
    telephone: '+81-980-87-0468',
    domestic: true,
    international: true,
  },
  'IBR': {
    name: '이바라키 공항',
    address: '733-3 Yotsukaido, Omitama, Ibaraki 311-3416, Japan',
    telephone: '+81-299-37-2800',
    domestic: true,
    international: true,
  },
  'KKJ': {
    name: '기타큐슈 공항',
    address: '6 Kugahara, Kokuraminami Ward, Kitakyushu, Fukuoka 800-0306, Japan',
    telephone: '+81-93-475-4195',
    domestic: true,
    international: true,
  },
  'OBO': {
    name: '오비히로 도카치 공항',
    address: 'Nishi-2-sen, Obihiro, Hokkaido 089-1240, Japan',
    telephone: '+81-155-64-5678',
    domestic: true,
    international: false,
  },
  'HKD': {
    name: '하코다테 공항',
    address: '511 Takamatsu-cho, Hakodate, Hokkaido 042-0952, Japan',
    telephone: '+81-138-57-8881',
    domestic: true,
    international: true,
  },
  'YGJ': {
    name: '요나고 기타로 공항',
    address: '1634 Sakai-minato, Tottori 684-0055, Japan',
    telephone: '+81-859-45-6121',
    domestic: true,
    international: true,
  },

  // ── 동아시아 - 중국 ──
  'PEK': {
    name: '베이징 서우두 국제공항',
    address: 'Capital Airport Rd, Chaoyang, Beijing, China',
    telephone: '+86-10-96158',
    domestic: true,
    international: true,
  },
  'PKX': {
    name: '베이징 다싱 국제공항',
    address: 'Daxing District, Beijing, China',
    telephone: '+86-10-96158',
    domestic: true,
    international: true,
  },
  'PVG': {
    name: '상하이 푸동 국제공항',
    address: 'S1 Yingbin Expressway, Pudong, Shanghai, China',
    telephone: '+86-21-96990',
    domestic: true,
    international: true,
  },
  'CAN': {
    name: '광저우 바이윈 국제공항',
    address: 'Renhe Town, Baiyun District, Guangzhou, Guangdong, China',
    telephone: '+86-20-96158',
    domestic: true,
    international: true,
  },
  'SZX': {
    name: '선전 바오안 국제공항',
    address: 'Bao\'an District, Shenzhen, Guangdong, China',
    telephone: '+86-755-23456789',
    domestic: true,
    international: true,
  },
  'TFU': {
    name: '청두 톈푸 국제공항',
    address: 'Jianyang, Chengdu, Sichuan, China',
    telephone: '+86-28-966666',
    domestic: true,
    international: true,
  },
  'CKG': {
    name: '충칭 장베이 국제공항',
    address: 'Yubei District, Chongqing, China',
    telephone: '+86-23-966666',
    domestic: true,
    international: true,
  },
  'DLC': {
    name: '다롄 저우수이쯔 국제공항',
    address: 'Ganjingzi District, Dalian, Liaoning, China',
    telephone: '+86-411-96600',
    domestic: true,
    international: true,
  },
  'TAO': {
    name: '칭다오 자오둥 국제공항',
    address: 'Jiaozhou, Qingdao, Shandong, China',
    telephone: '+86-532-96567',
    domestic: true,
    international: true,
  },
  'SHE': {
    name: '선양 타오셴 국제공항',
    address: 'Hunnan District, Shenyang, Liaoning, China',
    telephone: '+86-24-96833',
    domestic: true,
    international: true,
  },
  'HRB': {
    name: '하얼빈 타이핑 국제공항',
    address: 'Daoli District, Harbin, Heilongjiang, China',
    telephone: '+86-451-96368',
    domestic: true,
    international: true,
  },
  'XMN': {
    name: '샤먼 가오치 국제공항',
    address: 'Huli District, Xiamen, Fujian, China',
    telephone: '+86-592-96363',
    domestic: true,
    international: true,
  },
  'NKG': {
    name: '난징 루커우 국제공항',
    address: 'Jiangning District, Nanjing, Jiangsu, China',
    telephone: '+86-25-96889',
    domestic: true,
    international: true,
  },
  'HGH': {
    name: '항저우 샤오산 국제공항',
    address: 'Xiaoshan District, Hangzhou, Zhejiang, China',
    telephone: '+86-571-96299',
    domestic: true,
    international: true,
  },
  'KWL': {
    name: '구이린 량장 국제공항',
    address: 'Lingui District, Guilin, Guangxi, China',
    telephone: '+86-773-96888',
    domestic: true,
    international: true,
  },
  'CSX': {
    name: '장사 황화 국제공항',
    address: 'Changsha County, Changsha, Hunan, China',
    telephone: '+86-731-96777',
    domestic: true,
    international: true,
  },
  'WUH': {
    name: '우한 톈허 국제공항',
    address: 'Huangpi District, Wuhan, Hubei, China',
    telephone: '+86-27-96577',
    domestic: true,
    international: true,
  },
  'XIY': {
    name: '시안 셴양 국제공항',
    address: 'Weicheng District, Xianyang, Shaanxi, China',
    telephone: '+86-29-96789',
    domestic: true,
    international: true,
  },
  'KMG': {
    name: '쿤밍 창수이 국제공항',
    address: 'Guandu District, Kunming, Yunnan, China',
    telephone: '+86-871-96566',
    domestic: true,
    international: true,
  },
  'CGO': {
    name: '정저우 신정 국제공항',
    address: 'Xinzheng, Zhengzhou, Henan, China',
    telephone: '+86-371-96666',
    domestic: true,
    international: true,
  },
  'TNA': {
    name: '지난 야오창 국제공항',
    address: 'Lixia District, Jinan, Shandong, China',
    telephone: '+86-531-96888',
    domestic: true,
    international: true,
  },
  'CGQ': {
    name: '창춘 룽자 국제공항',
    address: 'Jiutai District, Changchun, Jilin, China',
    telephone: '+86-431-96666',
    domestic: true,
    international: true,
  },
  'TSN': {
    name: '톈진 빈하이 국제공항',
    address: 'Dongli District, Tianjin, China',
    telephone: '+86-22-96777',
    domestic: true,
    international: true,
  },
  'YNJ': {
    name: '옌지 차오양촨 공항',
    address: 'Chaoyangchuan, Yanji, Jilin, China',
    telephone: '+86-433-2131111',
    domestic: true,
    international: true,
  },
  'SJW': {
    name: '스자좡 정딩 국제공항',
    address: 'Zhengding County, Shijiazhuang, Hebei, China',
    telephone: '+86-311-96360',
    domestic: true,
    international: true,
  },
  'WUX': {
    name: '우시 수난 숴팡 국제공항',
    address: 'Xinwu District, Wuxi, Jiangsu, China',
    telephone: '+86-510-96889',
    domestic: true,
    international: true,
  },
  'FOC': {
    name: '푸저우 창러 국제공항',
    address: 'Changle District, Fuzhou, Fujian, China',
    telephone: '+86-591-96363',
    domestic: true,
    international: true,
  },
  'HFE': {
    name: '허페이 신차오 국제공항',
    address: 'Feixi County, Hefei, Anhui, China',
    telephone: '+86-551-96566',
    domestic: true,
    international: true,
  },
  'YNT': {
    name: '옌타이 펑라이 국제공항',
    address: 'Penglai District, Yantai, Shandong, China',
    telephone: '+86-535-96573',
    domestic: true,
    international: true,
  },
  'WEH': {
    name: '웨이하이 다수이보 국제공항',
    address: 'Wendeng District, Weihai, Shandong, China',
    telephone: '+86-631-5161666',
    domestic: true,
    international: true,
  },
  'YTY': {
    name: '양저우 타이저우 공항',
    address: 'Jiangdu District, Yangzhou, Jiangsu, China',
    telephone: '+86-514-89999999',
    domestic: true,
    international: true,
  },
  'YNZ': {
    name: '옌청 난양 공항',
    address: 'Tinghu District, Yancheng, Jiangsu, China',
    telephone: '+86-515-88888888',
    domestic: true,
    international: true,
  },
  'WNZ': {
    name: '원저우 룽완 국제공항',
    address: 'Longwan District, Wenzhou, Zhejiang, China',
    telephone: '+86-577-88339595',
    domestic: true,
    international: true,
  },
  'JMU': {
    name: '자무쓰 둥지아오 공항',
    address: 'Jiaoqu, Jiamusi, Heilongjiang, China',
    telephone: '+86-454-8685678',
    domestic: true,
    international: true,
  },
  'DYG': {
    name: '장가계 허화 공항',
    address: 'Yongding District, Zhangjiajie, Hunan, China',
    telephone: '+86-744-8238417',
    domestic: true,
    international: true,
  },
  'SYX': {
    name: '싼야 펑황 국제공항',
    address: 'Tianya District, Sanya, Hainan, China',
    telephone: '+86-898-88289389',
    domestic: true,
    international: true,
  },
  'HAK': {
    name: '하이커우 메이란 국제공항',
    address: 'Meilan District, Haikou, Hainan, China',
    telephone: '+86-898-65760114',
    domestic: true,
    international: true,
  },

  // ── 동아시아 - 대만 ──
  'TPE': {
    name: '타이완 타오위안 국제공항',
    address: 'No. 9, Hangzhan S. Rd., Dayuan Dist., Taoyuan City, Taiwan',
    telephone: '+886-3-2735081',
    domestic: false,
    international: true,
  },
  'KHH': {
    name: '가오슝 국제공항',
    address: 'No. 2, Zhongshan 4th Rd., Xiaogang Dist., Kaohsiung City, Taiwan',
    telephone: '+886-7-8057630',
    domestic: true,
    international: true,
  },
  'RMQ': {
    name: '타이중 국제공항',
    address: 'No. 161, Sec. 1, Zhonghang Rd., Xitun Dist., Taichung City, Taiwan',
    telephone: '+886-4-26155000',
    domestic: true,
    international: true,
  },
  'HUN': {
    name: '화롄 공항',
    address: 'No. 100, Zhongzheng Rd., Xincheng Township, Hualien County, Taiwan',
    telephone: '+886-3-8210768',
    domestic: true,
    international: false,
  },

  // ── 동아시아 - 홍콩/마카오 ──
  'HKG': {
    name: '홍콩 국제공항',
    address: '1 Sky Plaza Rd, Chek Lap Kok, Hong Kong',
    telephone: '+852-2181-8888',
    domestic: false,
    international: true,
  },
  'MFM': {
    name: '마카오 국제공항',
    address: 'Avenida do Aeroporto, Taipa, Macau',
    telephone: '+853-2886-1111',
    domestic: false,
    international: true,
  },

  // ── 동아시아 - 몽골 ──
  'UBN': {
    name: '칭기즈칸 국제공항',
    address: 'Sergelen, Tuv Province, Mongolia',
    telephone: '+976-7000-9977',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 태국 ──
  'BKK': {
    name: '수완나품 국제공항',
    address: '999 Moo 1, Nong Prue, Bang Phli, Samut Prakan 10540, Thailand',
    telephone: '+66-2-132-1888',
    domestic: true,
    international: true,
  },
  'DMK': {
    name: '돈므앙 국제공항',
    address: '222 Vibhavadi Rangsit Rd, Sanambin, Don Mueang, Bangkok 10210, Thailand',
    telephone: '+66-2-535-1192',
    domestic: true,
    international: true,
  },
  'CNX': {
    name: '치앙마이 국제공항',
    address: '60 Mahidol Rd, Su Thep, Mueang Chiang Mai, Chiang Mai 50200, Thailand',
    telephone: '+66-53-922-100',
    domestic: true,
    international: true,
  },
  'HKT': {
    name: '푸켓 국제공항',
    address: '222 Mai Khao, Thalang District, Phuket 83110, Thailand',
    telephone: '+66-76-351-167',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 베트남 ──
  'SGN': {
    name: '탄손녓 국제공항',
    address: 'Truong Son St, Ward 2, Tan Binh, Ho Chi Minh City, Vietnam',
    telephone: '+84-28-3848-5383',
    domestic: true,
    international: true,
  },
  'HAN': {
    name: '노이바이 국제공항',
    address: 'Phu Minh, Soc Son, Hanoi, Vietnam',
    telephone: '+84-24-3886-5047',
    domestic: true,
    international: true,
  },
  'DAD': {
    name: '다낭 국제공항',
    address: 'Hai Chau District, Da Nang, Vietnam',
    telephone: '+84-236-3823-397',
    domestic: true,
    international: true,
  },
  'CXR': {
    name: '캄라인 국제공항',
    address: 'Cam Ranh, Khanh Hoa, Vietnam',
    telephone: '+84-258-3989-918',
    domestic: true,
    international: true,
  },
  'PQC': {
    name: '푸꾸옥 국제공항',
    address: 'Cua Duong, Phu Quoc, Kien Giang, Vietnam',
    telephone: '+84-297-3799-268',
    domestic: true,
    international: true,
  },
  'HPH': {
    name: '깟비 국제공항',
    address: 'Le Hong Phong, Dong Khe, Ngo Quyen, Hai Phong, Vietnam',
    telephone: '+84-225-3876-611',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 싱가포르 ──
  'SIN': {
    name: '싱가포르 창이 국제공항',
    address: '80 Airport Boulevard, Singapore 819642',
    telephone: '+65-6595-6868',
    domestic: false,
    international: true,
  },

  // ── 동남아시아 - 필리핀 ──
  'MNL': {
    name: '니노이 아키노 국제공항',
    address: 'Airport Rd, Pasay, Metro Manila, Philippines',
    telephone: '+63-2-8877-1109',
    domestic: true,
    international: true,
  },
  'CEB': {
    name: '막탄-세부 국제공항',
    address: 'Lapu-Lapu City, Cebu 6015, Philippines',
    telephone: '+63-32-494-7777',
    domestic: true,
    international: true,
  },
  'KLO': {
    name: '칼리보 국제공항',
    address: 'Kalibo, Aklan, Philippines',
    telephone: '+63-36-268-4204',
    domestic: true,
    international: true,
  },
  'TAG': {
    name: '보홀 팡라오 국제공항',
    address: 'Panglao, Bohol, Philippines',
    telephone: '+63-38-510-0000',
    domestic: true,
    international: true,
  },
  'CRK': {
    name: '클라크 국제공항',
    address: 'Clark Freeport Zone, Angeles, Pampanga 2009, Philippines',
    telephone: '+63-45-499-1169',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 말레이시아 ──
  'KUL': {
    name: '쿠알라룸푸르 국제공항',
    address: '64000 KLIA, Sepang, Selangor, Malaysia',
    telephone: '+60-3-8777-8888',
    domestic: true,
    international: true,
  },
  'BKI': {
    name: '코타키나발루 국제공항',
    address: 'Kota Kinabalu, Sabah, Malaysia',
    telephone: '+60-88-325-555',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 인도네시아 ──
  'CGK': {
    name: '수카르노하타 국제공항',
    address: 'Pajang, Benda, Tangerang City, Banten 15126, Indonesia',
    telephone: '+62-21-5505-1111',
    domestic: true,
    international: true,
  },
  'DPS': {
    name: '응우라라이 국제공항',
    address: 'Jl. Raya Gusti Ngurah Rai, Tuban, Kuta, Badung, Bali 80362, Indonesia',
    telephone: '+62-361-9351-011',
    domestic: true,
    international: true,
  },
  'MDC': {
    name: '샘 라투랑이 국제공항',
    address: 'Mapanget, Manado, North Sulawesi, Indonesia',
    telephone: '+62-431-816-444',
    domestic: true,
    international: true,
  },
  'BTH': {
    name: '항나딤 국제공항',
    address: 'Batu Besar, Nongsa, Batam, Riau Islands, Indonesia',
    telephone: '+62-778-761-222',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 미얀마 ──
  'RGN': {
    name: '양곤 국제공항',
    address: 'Mingaladon, Yangon, Myanmar',
    telephone: '+95-1-533-030',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 라오스 ──
  'VTE': {
    name: '왓타이 국제공항',
    address: 'Vientiane, Laos',
    telephone: '+856-21-512-163',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 캄보디아 ──
  'KTI': {
    name: '프놈펜 국제공항',
    address: 'Phnom Penh, Cambodia',
    telephone: '+855-23-890-890',
    domestic: true,
    international: true,
  },

  // ── 동남아시아 - 브루나이 ──
  'BWN': {
    name: '브루나이 국제공항',
    address: 'Bandar Seri Begawan BB2513, Brunei',
    telephone: '+673-233-1747',
    domestic: false,
    international: true,
  },

  // ── 남아시아 ──
  'DEL': {
    name: '인디라 간디 국제공항',
    address: 'New Delhi 110037, India',
    telephone: '+91-124-337-6000',
    domestic: true,
    international: true,
  },
  'KTM': {
    name: '트리부반 국제공항',
    address: 'Kathmandu 44600, Nepal',
    telephone: '+977-1-4113-062',
    domestic: true,
    international: true,
  },
  'CMB': {
    name: '반다라나이케 국제공항',
    address: 'Canada Friendship Rd, Katunayake 11450, Sri Lanka',
    telephone: '+94-11-226-1291',
    domestic: false,
    international: true,
  },
  'DAC': {
    name: '하즈랏 샤잘랄 국제공항',
    address: 'Kurmitola, Dhaka 1229, Bangladesh',
    telephone: '+880-2-8914-990',
    domestic: true,
    international: true,
  },

  // ── 중앙아시아 ──
  'TAS': {
    name: '이슬람 카리모프 타슈켄트 국제공항',
    address: 'Tashkent, Uzbekistan',
    telephone: '+998-71-140-2801',
    domestic: true,
    international: true,
  },
  'ALA': {
    name: '알마티 국제공항',
    address: 'Almaty, Kazakhstan',
    telephone: '+7-727-270-3333',
    domestic: true,
    international: true,
  },
  'NQZ': {
    name: '누르술탄 나자르바예프 국제공항',
    address: 'Astana, Kazakhstan',
    telephone: '+7-717-270-2222',
    domestic: true,
    international: true,
  },
  'CIT': {
    name: '쉼켄트 국제공항',
    address: 'Shymkent, Kazakhstan',
    telephone: '+7-725-253-4444',
    domestic: true,
    international: true,
  },
  'BSZ': {
    name: '마나스 국제공항',
    address: 'Bishkek, Kyrgyzstan',
    telephone: '+996-312-693-109',
    domestic: true,
    international: true,
  },
  'ASB': {
    name: '아쉬가바트 국제공항',
    address: 'Ashgabat, Turkmenistan',
    telephone: '+993-12-23-08-22',
    domestic: true,
    international: true,
  },

  // ── 중동 ──
  'DXB': {
    name: '두바이 국제공항',
    address: 'Dubai, United Arab Emirates',
    telephone: '+971-4-224-5555',
    domestic: false,
    international: true,
  },
  'AUH': {
    name: '아부다비 국제공항',
    address: 'Abu Dhabi, United Arab Emirates',
    telephone: '+971-2-505-5555',
    domestic: false,
    international: true,
  },
  'DOH': {
    name: '하마드 국제공항',
    address: 'Doha, Qatar',
    telephone: '+974-4010-6666',
    domestic: false,
    international: true,
  },
  'IST': {
    name: '이스탄불 공항',
    address: 'Tayakadın, Terminal Cad No:1, 34283 Arnavutköy/İstanbul, Türkiye',
    telephone: '+90-212-463-3000',
    domestic: true,
    international: true,
  },

  // ── 유럽 ──
  'LHR': {
    name: '런던 히드로 공항',
    address: 'Longford TW6, United Kingdom',
    telephone: '+44-844-335-1801',
    domestic: true,
    international: true,
  },
  'CDG': {
    name: '파리 샤를 드 골 공항',
    address: '95700 Roissy-en-France, France',
    telephone: '+33-1-7036-3950',
    domestic: true,
    international: true,
  },
  'FRA': {
    name: '프랑크푸르트 공항',
    address: '60547 Frankfurt am Main, Germany',
    telephone: '+49-69-690-0',
    domestic: true,
    international: true,
  },
  'MUC': {
    name: '뮌헨 공항',
    address: 'Nordallee 25, 85356 München-Flughafen, Germany',
    telephone: '+49-89-975-00',
    domestic: true,
    international: true,
  },
  'AMS': {
    name: '암스테르담 스키폴 공항',
    address: 'Evert van de Beekstraat 202, 1118 CP Schiphol, Netherlands',
    telephone: '+31-20-794-0800',
    domestic: false,
    international: true,
  },
  'FCO': {
    name: '로마 피우미치노 공항',
    address: 'Via dell\'Aeroporto di Fiumicino, 00054 Fiumicino RM, Italy',
    telephone: '+39-06-65951',
    domestic: true,
    international: true,
  },
  'MXP': {
    name: '밀라노 말펜사 공항',
    address: '21010 Ferno VA, Italy',
    telephone: '+39-02-232323',
    domestic: true,
    international: true,
  },
  'MAD': {
    name: '마드리드 바라하스 공항',
    address: 'Av de la Hispanidad, s/n, 28042 Madrid, Spain',
    telephone: '+34-91-321-1000',
    domestic: true,
    international: true,
  },
  'BCN': {
    name: '바르셀로나 엘프라트 공항',
    address: '08820 El Prat de Llobregat, Barcelona, Spain',
    telephone: '+34-91-321-1000',
    domestic: true,
    international: true,
  },
  'PRG': {
    name: '바츨라프 하벨 프라하 공항',
    address: 'K Letišti 1019/6, 161 00 Praha 6, Czech Republic',
    telephone: '+420-220-111-888',
    domestic: false,
    international: true,
  },
  'VIE': {
    name: '빈 국제공항',
    address: '1300 Schwechat, Austria',
    telephone: '+43-1-7007-22233',
    domestic: false,
    international: true,
  },
  'HEL': {
    name: '헬싱키 반타 공항',
    address: 'Lentoasemantie, 01530 Vantaa, Finland',
    telephone: '+358-200-14636',
    domestic: true,
    international: true,
  },
  'CPH': {
    name: '코펜하겐 카스트럽 공항',
    address: 'Lufthavnsboulevarden 6, 2770 Kastrup, Denmark',
    telephone: '+45-3231-3231',
    domestic: true,
    international: true,
  },
  'WAW': {
    name: '바르샤바 쇼팽 공항',
    address: 'Żwirki i Wigury 1, 00-906 Warszawa, Poland',
    telephone: '+48-22-650-4220',
    domestic: true,
    international: true,
  },
  'WRO': {
    name: '브로츠와프 니콜라우스 코페르니쿠스 공항',
    address: 'ul. Graniczna 190, 54-530 Wrocław, Poland',
    telephone: '+48-71-358-1381',
    domestic: true,
    international: true,
  },
  'BUD': {
    name: '부다페스트 리스트 페렌츠 국제공항',
    address: 'Budapest, 1185, Hungary',
    telephone: '+36-1-296-7000',
    domestic: false,
    international: true,
  },
  'LIS': {
    name: '리스본 움베르투 델가두 공항',
    address: 'Alameda das Comunidades Portuguesas, 1700-111 Lisboa, Portugal',
    telephone: '+351-218-413-500',
    domestic: true,
    international: true,
  },

  // ── 북미 - 미국 ──
  'JFK': {
    name: '존 F. 케네디 국제공항',
    address: 'Queens, NY 11430, United States',
    telephone: '+1-718-244-4444',
    domestic: true,
    international: true,
  },
  'LAX': {
    name: '로스앤젤레스 국제공항',
    address: '1 World Way, Los Angeles, CA 90045, United States',
    telephone: '+1-310-646-5252',
    domestic: true,
    international: true,
  },
  'SFO': {
    name: '샌프란시스코 국제공항',
    address: 'San Francisco, CA 94128, United States',
    telephone: '+1-650-821-8211',
    domestic: true,
    international: true,
  },
  'ORD': {
    name: '시카고 오헤어 국제공항',
    address: '10000 W O\'Hare Ave, Chicago, IL 60666, United States',
    telephone: '+1-773-686-2200',
    domestic: true,
    international: true,
  },
  'SEA': {
    name: '시애틀-타코마 국제공항',
    address: '17801 International Blvd, Seattle, WA 98158, United States',
    telephone: '+1-206-787-5388',
    domestic: true,
    international: true,
  },
  'ATL': {
    name: '하츠필드-잭슨 애틀랜타 국제공항',
    address: '6000 N Terminal Pkwy, Atlanta, GA 30320, United States',
    telephone: '+1-404-530-6600',
    domestic: true,
    international: true,
  },
  'DFW': {
    name: '댈러스/포트워스 국제공항',
    address: '2400 Aviation Dr, DFW Airport, TX 75261, United States',
    telephone: '+1-972-973-3112',
    domestic: true,
    international: true,
  },
  'EWR': {
    name: '뉴어크 리버티 국제공항',
    address: '3 Brewster Rd, Newark, NJ 07114, United States',
    telephone: '+1-973-961-6000',
    domestic: true,
    international: true,
  },
  'IAD': {
    name: '워싱턴 덜레스 국제공항',
    address: '1 Saarinen Circle, Dulles, VA 20166, United States',
    telephone: '+1-703-572-2700',
    domestic: true,
    international: true,
  },
  'BOS': {
    name: '보스턴 로건 국제공항',
    address: '1 Harborside Dr, Boston, MA 02128, United States',
    telephone: '+1-617-568-5000',
    domestic: true,
    international: true,
  },
  'LAS': {
    name: '해리 리드 국제공항',
    address: '5757 Wayne Newton Blvd, Las Vegas, NV 89119, United States',
    telephone: '+1-702-261-5211',
    domestic: true,
    international: true,
  },
  'DTW': {
    name: '디트로이트 메트로폴리탄 웨인 카운티 공항',
    address: '11050 W Eureka Rd, Romulus, MI 48174, United States',
    telephone: '+1-734-247-7678',
    domestic: true,
    international: true,
  },
  'MSP': {
    name: '미니애폴리스-세인트폴 국제공항',
    address: '4300 Glumack Dr, St Paul, MN 55111, United States',
    telephone: '+1-612-726-5555',
    domestic: true,
    international: true,
  },
  'SLC': {
    name: '솔트레이크시티 국제공항',
    address: '776 N Terminal Dr, Salt Lake City, UT 84122, United States',
    telephone: '+1-801-575-2400',
    domestic: true,
    international: true,
  },
  'ANC': {
    name: '테드 스티븐스 앵커리지 국제공항',
    address: '5000 W International Airport Rd, Anchorage, AK 99502, United States',
    telephone: '+1-907-266-2525',
    domestic: true,
    international: true,
  },
  'HNL': {
    name: '대니얼 K. 이노우에 국제공항',
    address: '300 Rodgers Blvd, Honolulu, HI 96819, United States',
    telephone: '+1-808-836-6411',
    domestic: true,
    international: true,
  },
  'KOA': {
    name: '엘리슨 오니즈카 코나 국제공항',
    address: '73-200 Kupipi St, Kailua-Kona, HI 96740, United States',
    telephone: '+1-808-329-3423',
    domestic: true,
    international: true,
  },
  'GUM': {
    name: '안토니오 B. 원 팻 국제공항',
    address: '355 Chalan Pasaheru Rte 10A, Tamuning, Guam 96913',
    telephone: '+1-671-646-0300',
    domestic: false,
    international: true,
  },
  'SPN': {
    name: '사이판 국제공항',
    address: 'Saipan, MP 96950, Northern Mariana Islands',
    telephone: '+1-670-664-3500',
    domestic: false,
    international: true,
  },

  // ── 북미 - 캐나다 ──
  'YVR': {
    name: '밴쿠버 국제공항',
    address: '3211 Grant McConachie Way, Richmond, BC V7B 0A4, Canada',
    telephone: '+1-604-207-7077',
    domestic: true,
    international: true,
  },
  'YYZ': {
    name: '토론토 피어슨 국제공항',
    address: '6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada',
    telephone: '+1-416-247-7678',
    domestic: true,
    international: true,
  },

  // ── 중남미 ──
  'MEX': {
    name: '멕시코시티 국제공항',
    address: 'Av. Capitán Carlos León S/N, Peñón de los Baños, 15620 Ciudad de México, Mexico',
    telephone: '+52-55-2482-2400',
    domestic: true,
    international: true,
  },

  // ── 오세아니아 ──
  'SYD': {
    name: '시드니 킹스포드 스미스 공항',
    address: 'Airport Dr, Sydney NSW 2020, Australia',
    telephone: '+61-2-9667-9111',
    domestic: true,
    international: true,
  },
  'MEL': {
    name: '멜버른 공항',
    address: 'Airport Dr, Tullamarine VIC 3045, Australia',
    telephone: '+61-3-9297-1600',
    domestic: true,
    international: true,
  },
  'BNE': {
    name: '브리즈번 공항',
    address: '11 The Circuit, Brisbane Airport QLD 4008, Australia',
    telephone: '+61-7-3406-3000',
    domestic: true,
    international: true,
  },
  'AKL': {
    name: '오클랜드 공항',
    address: 'Ray Emery Dr, Auckland Airport, Mangere, Auckland 2022, New Zealand',
    telephone: '+64-9-275-0789',
    domestic: true,
    international: true,
  },

  // ── 아프리카 ──
  'ADD': {
    name: '아디스아바바 볼레 국제공항',
    address: 'Bole, Addis Ababa, Ethiopia',
    telephone: '+251-11-665-7700',
    domestic: true,
    international: true,
  },
  'CAI': {
    name: '카이로 국제공항',
    address: 'Heliopolis, Cairo Governorate, Egypt',
    telephone: '+20-2-2265-5000',
    domestic: true,
    international: true,
  },
};

export function getAirportInfo(airportCode: string): AirportInfo | null {
  return airportInfoMap[airportCode] || null;
}

export function getAllAirportInfo(): Record<string, AirportInfo> {
  return airportInfoMap;
}
